### Calculando QQ SSS

In [18]:
import pandas as pd
import os
import shutil
import openpyxl as op
import tkinter as tk
from tkinter import messagebox
import locale
from datetime import datetime, timedelta
import tkinter as tk
from tkinter import ttk
from ttkthemes import ThemedTk
import calendar
from dateutil.relativedelta import relativedelta
from openpyxl import load_workbook
from openpyxl.styles import Color, PatternFill, Font, Border
from openpyxl.utils.dataframe import dataframe_to_rows
import numpy as np
import xlwings as xw

In [19]:
###-----------------------------------------------Variáveis com datas----------------------------------------------###
locale.setlocale(locale.LC_TIME, 'pt_BR.utf-8')
hoje = datetime.now()

# Se hoje é segunda-feira, recuar 2 dias (para sábado); caso contrário, recuar 1 dia (para ontem)
if hoje.strftime('%A') == 'segunda-feira':
    date_time = hoje - timedelta(days=2)
else:
    date_time = hoje - timedelta(days=1)


data_hoje = hoje.date()

data_hoje_aaaamm = str(date_time.year) + '0' + str(date_time.month)
data_hoje_mm_aaaa = '0' + str(date_time.month) + '-' + str(date_time.year) 

data_ontem = date_time - timedelta(days=1)
data_ontem_aaaamm =  str(data_ontem.year) + '0' + str(data_ontem.month)

data_mes_anterior_mm_aaaa = '0' + str((data_ontem - relativedelta(months=1)).month) +'-' + str((data_ontem - relativedelta(months=1)).year)
data_mes_anterior_aaaamm = str((data_ontem - relativedelta(months=1)).year) + '0' + str((data_ontem - relativedelta(months=1)).month)
data_dois_meses_anteriores_aaaamm = str((data_ontem - relativedelta(months=2)).year) + '0' + str((data_ontem - relativedelta(months=2)).month)
data_tres_meses_anteriores_aaaamm = str((data_ontem - relativedelta(months=3)).year) + '0' + str((data_ontem - relativedelta(months=3)).month)

dia_anterior_dd_mm_aa = str(data_ontem.day) + '-' + str(data_ontem.month) + '-' + str(data_ontem.year)
dia_anterior_mm_aa = str(data_ontem.month) + '-' + str(data_ontem.year)

abrev_mes_ano_atual = (date_time - relativedelta(days=1)).strftime('%b/%y')
abrev_mes_ano_passado = (date_time - relativedelta(years=1)).strftime('%b/%y')
mes_anterior_abrev_mes_ano = (date_time - relativedelta(months=1)).strftime('%b/%y')
dois_meses_anteriores_abrev_mes_ano = (date_time - relativedelta(months=2)).strftime('%b/%y')
tres_meses_anteriores_abrev_mes_ano = (date_time - relativedelta(months=3)).strftime('%b/%y')

QNT_dias_no_mes = calendar.monthrange(date_time.year, date_time.month)[1]

###-----------------------------------------------Variáveis com datas----------------------------------------------###

In [24]:
#----------------------------------Arquivos em Excel------------------------------------------#
df_painel_mensal = pd.read_csv(f"M:/Vendas/Operacoes/002_ESTUDO_MNM/000_BASE_PAINEL/painel_mensal-{data_ontem_aaaamm}.csv", sep=";", encoding="latin1")
df_painel_mensal_mes_anterior = pd.read_csv(f"M:/Vendas/Operacoes/002_ESTUDO_MNM/000_BASE_PAINEL/painel_mensal-{data_mes_anterior_aaaamm}.csv", sep=";", encoding="latin1")
df_painel_mensal_2meses_anteriores = pd.read_csv(f"M:/Vendas/Operacoes/002_ESTUDO_MNM/000_BASE_PAINEL/painel_mensal-{data_dois_meses_anteriores_aaaamm}.csv", sep=";", encoding="latin1")
df_painel_mensal_3meses_anteriores = pd.read_csv(f"M:/Vendas/Operacoes/002_ESTUDO_MNM/000_BASE_PAINEL/painel_mensal-{data_tres_meses_anteriores_aaaamm}.csv", sep=";", encoding="latin1")
df_base_grupos = pd.read_csv("M:/Vendas/Operacoes/002_ESTUDO_MNM/data_base/Base Grupos/Base_Grupos.csv", sep=";")
df_cad_func = pd.read_csv("O:\CONTROLADORIA\CAD FUNC\cadfunc.CSV", sep=';', encoding="latin1")
df_base_lojas = pd.read_csv("P:\Base_Lojas\Base_Lojas_Gestao Analitica.csv", sep=';', encoding="latin1")
df_ticket_medio = pd.read_excel(r"M:\Vendas\Operacoes\002_ESTUDO_MNM\Desenvolvimento Relatório\Main\Ticket Medio Filtrado.xlsx")
df_trainees = pd.read_excel(r"M:\Vendas\Operacoes\002_ESTUDO_MNM\Desenvolvimento Relatório\Main\TRAINEES INTERINOS.xlsx")
planilha_modelo_formatada = pd.read_excel(r"M:\Vendas\Operacoes\002_ESTUDO_MNM\Desenvolvimento Relatório\Gabryel\layout.xlsx")
    
#----------------------------------Arquivos em Excel------------------------------------------#

## Juntantando nome de trainees e gerentes

In [25]:
# lista_filiais_trainees = df_trainees['FILIAL'].unique().tolist() #[671, 372, 339, 223, 620, 641, 513, 560, 420, 578, 357, 470, 68, 458]

# mapa_nomes = df_trainees.set_index('FILIAL')['NOME GERENTE'].to_dict()

# df.loc[df['FILIAL'].isin(lista_filiais_trainees), 'NOME'] = \
#     df.loc[df['FILIAL'].isin(lista_filiais_trainees), 'FILIAL'].map(mapa_nomes)

# df = df[~df['FILIAL'].isin(['203', '1'])]

# df['NOME']

## Pegando mesmas lojas no ticket medio

In [26]:
df_ticket_medio_resumo= pd.read_excel(os.path.join(r"O:\CONTROLADORIA\Ticket Médio\Relatórios Produção Controladoria 06-2025.xlsb"), sheet_name='Resumo')
df_mm_filtered = df_ticket_medio_resumo.loc[df_ticket_medio_resumo.loc[:,'Unnamed: 2'].isin(["Total SSS (Mesmas Lojas)"])]
prod_atual_sss = df_mm_filtered['Unnamed: 4'].sum()
prod_aa_sss = df_mm_filtered['Unnamed: 5'].sum()
cresc_sss = (prod_atual_sss-prod_aa_sss)/prod_aa_sss

In [27]:
print(prod_atual_sss)
print(prod_aa_sss)
print(cresc_sss)

107831373.42999998
116285768.04000002
-0.07270360554433367

In [28]:
def base_painel_prod(df_base_painel_prod):
    
    

    # Filtragem dos DataFrames
    filter_strtype = [30]
    filter_strtype2 = [31]
    filter_strtype3 = [42]
    filter_strtype4 = [50]
    df_prod_filtered   = df_base_painel_prod.loc[df_base_painel_prod['ID_INDICADOR'].isin([30])].copy()
    df_margin_filtered = df_base_painel_prod.loc[df_base_painel_prod['ID_INDICADOR'].isin([31])].copy()
    df_desc_filtered   = df_base_painel_prod.loc[df_base_painel_prod['ID_INDICADOR'].isin([42])].copy()
    df_lb_filtered     = df_base_painel_prod.loc[df_base_painel_prod['ID_INDICADOR'].isin([50])].copy()


    # Criação da coluna "DESCONTO" no DataFrame df_margin_filtered
    df_desc_filtered.loc[:,'DESC'] = df_desc_filtered.loc[:,'REAL_MES']
    df_desc_filtered.loc[:,'DESC']=pd.to_numeric(df_desc_filtered.loc[:,'DESC'].replace(',', '.'), errors='coerce')

    # Criação da coluna "LUCRO BRUTO" no DataFrame df_margin_filtered
    df_lb_filtered.loc[:,'LB_REAL'] = df_lb_filtered.loc[:,'REAL_MES']
    df_lb_filtered.loc[:,'LB_ORC'] = df_lb_filtered.loc[:,'ORC_MES']
    df_lb_filtered.loc[:,'LB_REAL']=pd.to_numeric(df_lb_filtered.loc[:,'LB_REAL'].replace(',', '.'), errors='coerce')
    df_lb_filtered.loc[:,'LB_ORC']=pd.to_numeric(df_lb_filtered.loc[:,'LB_ORC'].replace(',', '.'), errors='coerce')
    df_lb_filtered.loc[:,'LB_ATING'] = df_lb_filtered.apply(lambda row: row['LB_REAL'] / row['LB_ORC'] if row['LB_ORC'] != 0 else 0, axis=1)       

    # Criação da coluna "MARGEM" no DataFrame df_margin_filtered
    df_margin_filtered.loc[:,'MARGEM'] = df_margin_filtered.loc[:,'REAL_MES']
    df_margin_filtered.loc[:,'MARGEM']=pd.to_numeric(df_margin_filtered.loc[:,'MARGEM'].replace(',', '.'), errors='coerce')
 
    # Conversão das colunas para números
    numeric_columns = ['REAL_MES', 'ORC_MES', 'META_MES']
    df_prod_filtered[numeric_columns] = df_prod_filtered[numeric_columns].apply(lambda x: pd.to_numeric(x.replace(',', '.'), errors='coerce'))
 
    # Cálculo das colunas "ATING" e "PROJ" no DataFrame df_prod_filtered
    df_prod_filtered.loc[:,'ATING'] = df_prod_filtered.apply(lambda row: row['REAL_MES'] / row['ORC_MES'] if row['ORC_MES'] != 0 else 0, axis=1)
    df_prod_filtered.loc[:,'PROJ'] = df_prod_filtered.loc[:,'ATING'] * df_prod_filtered.loc[:,'META_MES']

    # Mesclagem dos DataFrames
    df_prod_final = pd.merge(df_prod_filtered, df_margin_filtered[['FILIAL', 'MARGEM']], on='FILIAL', how='left')
    df_prod_final = pd.merge(df_prod_final,df_desc_filtered[['FILIAL','DESC']],on='FILIAL',how='left')
    df_prod_final = pd.merge(df_prod_final,df_lb_filtered[['FILIAL','LB_REAL','LB_ATING']],on='FILIAL',how='left')

    df_prod_final.loc[:,'REAL_DIA']=pd.to_numeric(df_prod_final.loc[:,'REAL_DIA'].replace(',', '.'), errors='coerce')   
    df_prod_final = df_prod_final[['FILIAL', 'REAL_DIA', 'REAL_MES', 'ATING', 'PROJ', 'META_MES','MARGEM','DESC', 'LB_REAL','LB_ATING','ORC_MES']]

    return df_prod_final

In [33]:
df_base_painel_prod = df_painel_mensal

def ating_rede():

    filter_strtype = [30]
    df_prod_filtered2 = df_base_painel_prod.loc[df_base_painel_prod.loc[:,'ID_INDICADOR'].isin(filter_strtype)]

    # Conversão das colunas para números
    numeric_columns = ['REAL_MES', 'ORC_MES', 'META_MES']
    df_prod_filtered2[numeric_columns] = df_prod_filtered2[numeric_columns].apply(lambda x: pd.to_numeric(x.replace(',', '.'), errors='coerce'))
    if df_prod_filtered2['REAL_MES'].isnull().any() or df_prod_filtered2['ORC_MES'].isnull().any():
        print("O DataFrame contém valores ausentes.")
    else:
        # Somar todos os elementos de A
        soma_A = df_prod_filtered2['REAL_MES'].sum()

        # Somar todos os elementos de B
        soma_B = df_prod_filtered2['ORC_MES'].sum()

        # Verificar se a soma de B é diferente de zero
        if soma_B == 0:
            print("A soma de B é zero, impossível dividir.")
        else:
            # Dividir soma de A por soma de B
            resultado = soma_A / soma_B

            print(f'Teste para verificar se aqui esta o valor de projeção da rede: {resultado}')
    return

In [35]:
print(ating_rede())

O DataFrame contém valores ausentes.
None

C:\Users\990211\AppData\Local\Temp\ipykernel_18448\2952886792.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_prod_filtered2[numeric_columns] = df_prod_filtered2[numeric_columns].apply(lambda x: pd.to_numeric(x.replace(',', '.'), errors='coerce'))

In [37]:

arquivo = 'P:\RelatorioVagasDiario.xlsx'

# Lista todas as abas
abas = pd.ExcelFile(arquivo).sheet_names
print("Abas disponíveis:", abas)

# Leia todas e veja quais têm os dados brutos
for aba in abas:
    print(f'\nPrévia da aba: {aba}')
    df = pd.read_excel(arquivo, sheet_name=aba)

df

Abas disponíveis: ['GRÁFICOS', 'VAGAS', 'DESPONTES', 'GRUPOS']

Prévia da aba: GRÁFICOS

Prévia da aba: VAGAS

c:\Users\990211\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

Prévia da aba: DESPONTES

Prévia da aba: GRUPOS

,Listagem de funções e seus respectivos grupos considerados no relatório:,Unnamed: 1
0,NaN,NaN
1,FUNÇÃO,GRUPO
2,ANALISTA DE CREDITO,ADMINISTRATIVO
3,ASSESSOR DE SERVICOS,ADMINISTRATIVO
4,ASSISTENTE ADMINISTRATIVO,ADMINISTRATIVO
5,AUXILIAR ADMINISTRATIVO,ADMINISTRATIVO
6,CAIXA,ADMINISTRATIVO
7,COORDENADOR ADMINISTRATIVO,ADMINISTRATIVO
8,COORDENADOR ADMINISTRATIVO II,ADMINISTRATIVO
9,AUXILIAR DE ESTOQUES,ESTOQUE
10,AUXILIAR DE MONTAGEM,ESTOQUE
11,AUXILIAR DE SERVICOS GERAIS,ESTOQUE
12,AUXILIAR DE SERVICOS GERAIS II,ESTOQUE
13,CONFERENTE CARGA,ESTOQUE
14,CONFERENTE DE EXPEDICAO,ESTOQUE
15,CONFERENTE I,ESTOQUE
16,ENCARREGADO DE CONFERENCIA,ESTOQUE
17,ENCARREGADO DE EXPEDICAO,ESTOQUE
18,MONTADOR MOVEIS,ESTOQUE
19,MOTORISTA,ESTOQUE
20,OPERADOR DE EMPILHADEIRA,ESTOQUE
21,COORDENADOR DE DEPOSITO,ESTOQUE
22,COORDENADOR DE ESTOQUE,ESTOQUE
23,ESTOQUISTA,ESTOQUE
24,SUPERVISOR DE ESTOQUE,ESTOQUE
25,GERENTE DE ESTOQUE,ESTOQUE
26,AUXILIAR OPERACIONAL,ESTOQUE
27,COORDENADOR DE VENDAS,VENDAS
28,SUPERVISOR DE VENDAS,VENDAS
29,GERENTE DE VENDAS,VENDAS
30,AUXILIAR PROJETISTA,VENDAS
31,CONSULTOR DE VENDAS,VENDAS
32,CONSULTOR DE VENDAS OUTLET,VENDAS
33,CONSULTOR ESPECIALISTA EM MATERIAL DE CONSTRUCAO,VENDAS
34,CONSULTOR PROJETISTA DE MOVEIS,VENDAS
35,VENDEDOR EXTERNO,VENDAS
36,VENDEDOR(A),VENDAS
37,CONSULTOR ESPECIALISTA EM TINTAS,VENDAS
38,ASSISTENTE DE COMPRAS,OUTROS
39,AUXILIAR DE COMPRAS,OUTROS
40,COMPRADOR,OUTROS
41,COBRADOR,OUTROS
42,COZINHEIRA,OUTROS
43,PROMOTOR DO CARTAO,OUTROS
44,SERVENTE,OUTROS
45,SERVENTE II,OUTROS